language: d
sudo: false

# Enable core dumps
before_script:
  - ulimit -c unlimited -S
  - sudo mkdir /cores/ && sudo chmod 777 /cores/
  - echo "/cores/%E.%p" | sudo tee /proc/sys/kernel/core_pattern

after_failure:
  - ./scripts/core-dump.sh

matrix:
  include:
    - d: dmd-nightly
    - d: dmd
    - d: ldc
  allow_failures:
    - d: dmd-nightly


script: ./ci.sh
